default: &default
  adapter: postgresql
  encoding: unicode  
  pool: 5

development:
  <<: *default
  database: ror_gap_test_development

test:
  <<: *default
  database: ror_gap_test_test

production:
  <<: *default
  database: ror_gap_test_production
  username: ror-gap-test
  password: <%= ENV['ROR_GAP_TEST_DATABASE_PASSWORD'] %>
